name: Integration

on:
  pull_request:
    branches:
      - master

jobs:
  integration:
    uses: djachenko/repokit/.github/workflows/python-integration.yml@0.3
    with:
      package_name: shabbot
    secrets: inherit
    permissions:
      id-token: write
