name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    uses: djachenko/repokit/.github/workflows/python-release.yml@0.3
    with:
      package_name: shabbot
    secrets: inherit
    permissions:
      id-token: write
      contents: write
